apiVersion: apps/v1
kind: Deployment
metadata:
  name: dizvik-deployment
  labels:
    app: dizvik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dizvik
  template:
    metadata:
      labels:
        app: dizvik
    spec:
      containers:
        - name: dizvik
          image: dizvikvishal/argoci:latest
          ports:
            - containerPort: 80
